### PR TITLE
call jshint with stdin, instead of filePath arg

### PR DESCRIPTION
**Pull request by harrytruong**
Depends on https://github.com/AtomLinter/Linter/pull/556
Closes issue https://github.com/AtomLinter/linter-jshint/issues/25 "Look for config in package.json"

~~**DO NOT MERGE**, unless https://github.com/AtomLinter/Linter/pull/556 is merged.~~
**DO NOT MERGE**, until new AtomLinter/Linter PR is submitted. On hold due to `LinterPlus` rewrite.

### CODE REVIEW

**Comment by harrytruong** [comment]
**DO NOT MERGE**, unless https://github.com/AtomLinter/Linter/pull/556 is merged. 

Note: I don't know how to declare the Linter version dependency. Is that even possible?

**Comment by steelbrain** [comment]
Already fixed by the rewrite

**Comment by harrytruong** [comment]
:+1:  it's beautiful, thanks so much!

**Comment by steelbrain** [comment]
Pleasure :bow:

**Pull request closed without merging**
