### PR TITLE
set syntax to only source.js

### PR DESCRIPTION
**Pull request by imperez**
Set the syntax to only source.js since .html or .js.jquery aren't standard file types.\

This should fix Issues #21 and #20.

### CODE REVIEW

**Comment by iam4x** [comment]
We can add this as "hotfix", the best way to achieve this it to add a configuration option to set manually the files syntax.

I'm okey to merge it, anyone want to add something?

**Comment by sdornan** [comment]
I also need this.

**Comment by defeated** [comment]
> anyone want to add something

just ran into #21 so :+1: to merging this hotfix!

**Comment by iam4x** [comment]
I'll assume it's okey!

**Comment by klebba** [comment]
This makes it impossible to lint inline script -- a serious shortcoming compared to https://github.com/SublimeLinter/SublimeLinter-jshint:

```
It will be used with files that have the “JavaScript” syntax, or within <script> tags in HTML files.
```

**Pull request merged**
