### PR TITLE
Remove helper URLs

### LINKED ISSUE #316: Broken Links
Error numbers have clickable links that go to a dead domain.  Example:
[W098](http://jslinterrors.com/W098) - 'data' is defined but never used.

I'm not sure if this is fixable, beyond simply ripping the links out entirely.

### PR DESCRIPTION
**Pull request by Arcanemagus**
jslinterrors.com has been dead for a while, and shows no sign of re-emerging any time soon.

Fixes #316.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Blocked on #336, which is just waiting on the Travis-CI OS X build.

**Comment by rugk** [comment]
You found no alternative site? :cry:

**Comment by Arcanemagus** [comment]
I don't use JSHint, so if there is one I don't know of it. Nobody has suggested one so far. If you find one feel free to file a new issue about it 😉.

**Comment by per1234** [comment]
Since I don't use this project, I don't know if you've already found an alternative site but you should know the site has since been reopened at linterrors.com/js:
https://github.com/jamesallardice/jslint-error-explanations/issues/39#issuecomment-250028253
https://github.com/jamesallardice/jslint-error-explanations/commit/54de6c5fd5a7d12155ea42bdac2c9c860a205ee2#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request merged**
